#!/bin/bash
# příprava experimentu

shopt -s expand_aliases
alias pow='python -c "from sys import argv as a; print(pow(float(a[1]), float(a[2])))"'

for i in cc-pvdz cc-pvtz 6-31g :
  do
    cp input tmp1
    sed -i "s/XXXXX/${i}/g" tmp1
    mv tmp1 input.$i
    #k = 0
    for j in $(seq -8.3333 0.3333 -5.000);
      do
	#echo $(echo $(pow 10 $j) | sed -e 's/[eE]+*/\*10\^/' | bc -l)
	
	#echo $k
	 cp input.$i tmp_pno
	sed -i "s/ZZZZZ/$(echo $(pow 10 $j) | sed -e 's/[eE]+*/\*10\^/' | bc -l)/g" tmp_pno
	mv tmp_pno input.${i}.${j}
      done

  done
